import type { Artwork } from '@/types'

export const localMedia = {
  hero: {
    background: '/abstract1.jpg',
    floatingLeft: '/africanart1.jpg',
    floatingRight: '/mixedmedia3.jpg',
  },
  artist: {
    portrait: '/thandazanindlovu.jpg',
    signatureWorks: ['/potrait1.jpg', '/africanart2.jpg', '/mixedmedia1.jpg'],
  },
  artworks: {
    abstract: ['/abstract1.jpg'],
    africanArt: ['/africanart1.jpg', '/africanart2.jpg', '/africanart3.jpg'],
    mixedMedia: ['/mixedmedia1.jpg', '/mixedmedia2.jpg', '/mixedmedia3.jpg', '/mixedmedia4.jpg'],
    portraits: ['/potrait1.jpg', '/potrait2.jpeg', '/potrait3.jpg', '/potrait4.jpg'],
  },
  social: {
    galleryInstagram: ['/gginstagram1.jpg', '/gginstagram2.jpg', '/gginstagram3.jpg', '/gginstagram4.jpg'],
    artistInstagram: ['/tninstagram1.jpeg', '/tninstagram2.jpg', '/tninstagram3.jpg', '/tninstagram4.jpg'],
    tiktok: ['/tiktok1.jpg', '/tiktok2.jpg', '/tiktok3.jpg', '/tiktok4.jpg'],
  },
  video: {
    walkthrough: '/gallerywalkthrough.mp4',
    poster: '/gginstagram2.jpg',
  },
} as const

export const fallbackArtworks = [
  {
    id: 'local-portrait-1',
    image: localMedia.artworks.portraits[0],
    artist: 'Thandazani Ndlovu',
    title: 'Echoes of the Ancestors',
    medium: 'Oil on Canvas',
    year: 2025,
    category: 'Portraits',
    aspect: 'aspect-[3/4]',
  },
  {
    id: 'local-mixed-1',
    image: localMedia.artworks.mixedMedia[0],
    artist: 'Thandazani Ndlovu',
    title: 'Urban Rhythm',
    medium: 'Mixed Media',
    year: 2024,
    category: 'Mixed Media',
    aspect: 'aspect-square',
  },
  {
    id: 'local-african-1',
    image: localMedia.artworks.africanArt[0],
    artist: 'Thandazani Ndlovu',
    title: 'Ancestral Lines',
    medium: 'Acrylic on Canvas',
    year: 2026,
    category: 'African Art',
    aspect: 'aspect-[4/5]',
  },
  {
    id: 'local-abstract-1',
    image: localMedia.artworks.abstract[0],
    artist: 'Thandazani Ndlovu',
    title: 'Abstract Landscapes II',
    medium: 'Acrylic on Linen',
    year: 2025,
    category: 'Abstract',
    aspect: 'aspect-[16/9]',
  },
  {
    id: 'local-mixed-3',
    image: localMedia.artworks.mixedMedia[2],
    artist: 'Thandazani Ndlovu',
    title: 'Texture Study I',
    medium: 'Mixed Media',
    year: 2024,
    category: 'Mixed Media',
    aspect: 'aspect-[3/4]',
  },
] as const

export const fallbackCollectionArtworks: Artwork[] = [
  {
    id: 'local-portrait-1',
    title: 'Echoes of the Ancestors',
    artist: 'Thandazani Ndlovu',
    medium: 'Oil on Canvas',
    size: '120 x 90 cm',
    year: 2025,
    category: 'Portraits',
    price: 45000,
    currency: 'ZAR',
    availability: 'Available',
    description: 'A deeply spiritual work exploring ancestral memory through layered oil paint and earthy tones.',
    image_url: localMedia.artworks.portraits[0],
    is_featured: true,
    sort_order: 1,
    created_at: '2026-05-28T00:00:00.000Z',
    updated_at: '2026-05-28T00:00:00.000Z',
  },
  {
    id: 'local-mixed-1',
    title: 'Urban Rhythm',
    artist: 'Thandazani Ndlovu',
    medium: 'Mixed Media',
    size: '100 x 100 cm',
    year: 2024,
    category: 'Mixed Media',
    price: 38000,
    currency: 'ZAR',
    availability: 'Available',
    description: 'An exploration of city life through overlapping textures and urban materials.',
    image_url: localMedia.artworks.mixedMedia[0],
    is_featured: true,
    sort_order: 2,
    created_at: '2026-05-27T00:00:00.000Z',
    updated_at: '2026-05-27T00:00:00.000Z',
  },
  {
    id: 'local-african-1',
    title: 'Ancestral Lines',
    artist: 'Thandazani Ndlovu',
    medium: 'Acrylic on Canvas',
    size: '90 x 120 cm',
    year: 2026,
    category: 'African Art',
    price: 52000,
    currency: 'ZAR',
    availability: 'Reserved',
    description: 'Intricate mark-making drawing on traditional African geometric patterns.',
    image_url: localMedia.artworks.africanArt[0],
    is_featured: true,
    sort_order: 3,
    created_at: '2026-05-26T00:00:00.000Z',
    updated_at: '2026-05-26T00:00:00.000Z',
  },
  {
    id: 'local-abstract-1',
    title: 'Abstract Landscapes II',
    artist: 'Thandazani Ndlovu',
    medium: 'Acrylic on Linen',
    size: '150 x 80 cm',
    year: 2025,
    category: 'Abstract',
    price: 52000,
    currency: 'ZAR',
    availability: 'Available',
    description: 'Bold abstract forms inspired by the South African landscape.',
    image_url: localMedia.artworks.abstract[0],
    is_featured: true,
    sort_order: 4,
    created_at: '2026-05-25T00:00:00.000Z',
    updated_at: '2026-05-25T00:00:00.000Z',
  },
  {
    id: 'local-portrait-2',
    title: 'Golden Hour',
    artist: 'Thandazani Ndlovu',
    medium: 'Oil on Canvas',
    size: '80 x 60 cm',
    year: 2025,
    category: 'Portraits',
    price: 35000,
    currency: 'ZAR',
    availability: 'Available',
    description: 'Capturing the magical light of an African sunset in bold, gestural strokes.',
    image_url: localMedia.artworks.portraits[1],
    is_featured: false,
    sort_order: 5,
    created_at: '2026-05-24T00:00:00.000Z',
    updated_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'local-mixed-2',
    title: 'Texture Study I',
    artist: 'Thandazani Ndlovu',
    medium: 'Mixed Media',
    size: '90 x 90 cm',
    year: 2024,
    category: 'Mixed Media',
    price: 42000,
    currency: 'ZAR',
    availability: 'Sold',
    description: 'A meditation on light, surface, and layered memory.',
    image_url: localMedia.artworks.mixedMedia[2],
    is_featured: false,
    sort_order: 6,
    created_at: '2026-05-23T00:00:00.000Z',
    updated_at: '2026-05-23T00:00:00.000Z',
  },
  {
    id: 'local-african-2',
    title: 'The Gathering',
    artist: 'Thandazani Ndlovu',
    medium: 'Acrylic on Canvas',
    size: '200 x 150 cm',
    year: 2023,
    category: 'African Art',
    price: 75000,
    currency: 'ZAR',
    availability: 'Sold',
    description: 'A monumental work depicting community, resilience, and shared identity.',
    image_url: localMedia.artworks.africanArt[2],
    is_featured: false,
    sort_order: 7,
    created_at: '2026-05-22T00:00:00.000Z',
    updated_at: '2026-05-22T00:00:00.000Z',
  },
  {
    id: 'local-mixed-3',
    title: 'Urban Chaos',
    artist: 'Thandazani Ndlovu',
    medium: 'Mixed Media',
    size: '120 x 120 cm',
    year: 2025,
    category: 'Mixed Media',
    price: 58000,
    currency: 'ZAR',
    availability: 'Available',
    description: 'The energy and disorder of urban African life rendered in abstract form.',
    image_url: localMedia.artworks.mixedMedia[3],
    is_featured: false,
    sort_order: 8,
    created_at: '2026-05-21T00:00:00.000Z',
    updated_at: '2026-05-21T00:00:00.000Z',
  },
]
